__title__ = "gamma-launcher"
__description__ = "G.A.M.M.A. Launcher module"
__url__ = "https://github.com/Mord3rca/gamma-launcher"
__version__ = "1.1"
__author__ = "Mord3rca"
__author_email__ = "morderca@morderca.net"
__license__ = "GPLv3"
