name: Build-All-Platforms

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-18.04, windows-latest ]
        python-version: [ "3.10", ]

    runs-on: ${{ matrix.os }}

    steps:
      # Check-out repository
      - uses: actions/checkout@v3

      # Setup python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      # Install fuse
      - name: Install fuse
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

      # Build python script into a stand-alone exe with nuitka
      - uses: jimkring/python-script-to-exe@v0.2.0
        with:
          script-name: launcher/cli.py
          onefile: true

      # Uploads artifacts
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*