name: Build-All-Platforms

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.10", ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install Nuitka

      - name: "Install fuse"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

#      - name: "Manual compile with nuitka in linux"
#        if: runner.os == 'Linux'
#        run: |
#          nuitka3 --onefile --remove-output launcher/cli.py

      - name: "Manual compile with nuitka in windows"
        if: runner.os == 'Windows'
        run: |
          dir
          cd
          nuitka --onefile --remove-output launcher/cli.py

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            *.bin
            *.exe