name: Generate Standalone Executable

on:
  release:
    types: [created]

jobs:
  generate:

    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              artifact_name: artifacts/gamma-launcher
            - os: windows-latest
              artifact_name: artifacts/gamma-launcher.exe

    name: Create Artifacts
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . pyinstaller
    - name: Build executable
      run: bash .github/scripts/release.sh
    - name: Upload artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
